name: test_drive
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: 4.2.0
  location_permissions: ^4.0.0
  flutter_reactive_ble: 5.0.3
  speedometer: ^1.0.1
  rxdart: 0.26.0
  battery_indicator: 0.1.2
  flex_color_picker: ^3.2.2
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  